sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t apupatil/docker-first -f Dockerfile.dev .

script:
  - docker run -e CI=true apupatil/docker-first npm run test 


